plugins {
    id 'com.android.library'
}

android {
    namespace 'com.android.settingslib.utils'

    defaultConfig {
        minSdk 21
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    sourceSets {
        main {
            res.srcDirs = ['../fwb/packages/SettingsLib/Utils/res']
            java.srcDirs = ['../fwb/packages/SettingsLib/Utils/src']
        }
    }
}

dependencies {
    compileOnly libs.annotation
}
