pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

buildscript {
    ext {
        agpVersion = new File(rootProject.projectDir.absoluteFile, "gradle/libs.versions.toml")
            .readLines()
            .stream()
            .filter((line) -> line.startsWith("agp ="))
            .map((line) -> line.split('"')[1])
            .findFirst()
            .get()
    }
}

plugins {
    id 'com.android.settings' version "${agpVersion}"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = '7SIM'

include ':SettingsLib:BannerMessagePreference'
include ':SettingsLib:ButtonPreference'
include ':SettingsLib:CollapsingToolbarBaseActivity'
include ':SettingsLib:LayoutPreference'
include ':SettingsLib:SettingsTheme'
include ':SettingsLib:SettingsThemeFlags'
include ':SettingsLib:TwoTargetPreference'

android {
    compileSdk 36
    minSdk 29
    targetSdk 36
    buildToolsVersion '36.0.0'
}
