plugins {
    id 'com.android.application'
    id 'kotlin-kapt'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'org.lineageos.settings'

    defaultConfig {
        applicationId 'org.lineageos.settings'
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        platform {
            storeFile file('platform.jks')
            storePassword 'android'
            keyAlias 'platform'
            keyPassword 'android'
        }
    }

    buildTypes {
        all {
            signingConfig signingConfigs.platform
        }
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'src/main/proguard.flags'
        }
    }

    sourceSets {
        main {
            java.srcDirs = ['src/main/java/']
        }
    }

    lint {
        disable 'ProtectedPermissions'
        disable 'MissingTranslation'
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    implementation libs.core
    implementation libs.material
    implementation libs.preference

    implementation project(path: ':SettingsLib:CollapsingToolbarBaseActivity')
    implementation project(path: ':SettingsLib:FooterPreference')
    implementation project(path: ':SettingsLib:IllustrationPreference')
    implementation project(path: ':SettingsLib:MainSwitchPreference')
    implementation project(path: ':SettingsLib:SettingsTheme')
    implementation project(path: ':SettingsLib:SliderPreference')

    implementation libs.hilt_android
    kapt libs.hilt_compiler
}

kapt {
    correctErrorTypes true
}
