import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {
    ext {
        jars = [
            android_hidden       :  'android-36.jar'
        ]
    }

    dependencies {
        classpath "io.github.takahirom.roborazzi:roborazzi-gradle-plugin:${libs.versions.roborazzi.get()}"
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.errorprone) apply false
    alias(libs.plugins.kover) apply false
    alias(libs.plugins.roborazzi) apply false
}

allprojects {
    plugins.withType(JavaBasePlugin).configureEach {
        java {
            toolchain {
                languageVersion.set(JavaLanguageVersion.of(21))
            }
        }
    }

    ext {
        addCompileOnlyJar = { String name, boolean requiredByAndroidTest = false ->
            final def jars_dir = "$rootDir/prebuilts/jars"
            final def jar = new File(jars_dir, name)
            if (!jar.exists()) {
                throw new IllegalArgumentException("Cannot find prebuilt '${jar.path}' file.")
            }
            gradle.projectsEvaluated {
                tasks.withType(JavaCompile).configureEach {
                    classpath = files(jar, classpath)
                }
                tasks.withType(KotlinCompile).configureEach {
                    libraries.from(files(jar))
                }
            }
            dependencies {
                compileOnly files(jar)
                if (requiredByAndroidTest) {
                    androidTestCompileOnly files(jar)
                }
            }
        }
    }
}

apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'kotlin-kapt'
apply plugin: 'net.ltgt.errorprone'
apply plugin: 'org.jetbrains.kotlinx.kover'
apply plugin: 'io.github.takahirom.roborazzi'

final def versionNameCommon = [file('version.txt').text.trim()]
if (System.getenv('EXTRA_VERSION_BUILD_INFO') == null) {
    final def tag = 'v' + versionNameCommon[0]
    final def (semver, commitsSinceLastTag, headCommit) = gitDescribeTag(tag, 'HEAD')
    versionNameCommon.add('git branch --show-current'.execute([], project.rootDir).text.trim())
    versionNameCommon.add(String.format('%s+%s', headCommit, commitsSinceLastTag))
} else {
    final def extraVersionBuildInfo = System.getenv('EXTRA_VERSION_BUILD_INFO').trim()
    if (!extraVersionBuildInfo.isEmpty()) {
        versionNameCommon.add(extraVersionBuildInfo)
    }
}

configurations.create("mockitoAgent") {
    transitive = false
}

tasks.withType(Test) {
    jvmArgs("-javaagent:${configurations.mockitoAgent.asPath}")
}

android {
    namespace 'com.github.iusmac.sevensim'

    defaultConfig {
        applicationId 'com.github.iusmac.sevensim'
        versionCode versionNameCommon[0].replaceAll(/\D/, '') as Integer // "x.y.z" => xyz
        testInstrumentationRunner 'com.github.iusmac.sevensim.HiltTestRunner'
        kapt {
            arguments {
                arg("room.schemaLocation", "$projectDir/schemas")
            }
        }
    }

    applicationVariants.all { variant ->
        final def versionNameVariant = versionNameCommon.clone()
        if (variant.buildType.isDebuggable()) {
            versionNameVariant.add('DEBUG')
        } else if (isReleaseDebugOpt()) {
            versionNameVariant.add('DEBUG-OPT')
        }
        variant.outputs.each { output ->
            final def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                final semVer = versionNameCommon[0]
                output.outputFileName = String.format('%s-%s-%s.apk', project.name, semVer,
                        variant.buildType.name)
            }
            output.versionNameOverride = versionNameVariant.join(' / ')
        }
    }

    final def keystoreProperties = new Properties()
    keystoreProperties.load(new FileInputStream(file('keystore.properties')))
    def releaseSigning = signingConfigs.create('release') {
        keyAlias keystoreProperties['keyAlias']
        keyPassword keystoreProperties['keyPassword']
        storeFile file(keystoreProperties['storeFile'])
        storePassword keystoreProperties['storePassword']
    }

    buildTypes {
        all {
            buildConfigField 'boolean', 'DEBUG_OPT', 'false'
            signingConfig releaseSigning
        }
        release {
            buildConfigField 'boolean', 'DEBUG_OPT', isReleaseDebugOpt().toString()
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard.flags'
        }
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            manifest.srcFile 'AndroidManifest.xml'
        }

        test.java.srcDirs += 'tests/test/java'

        debug.assets.srcDirs += files("$projectDir/schemas".toString())
        release.assets.srcDirs += files("$projectDir/schemas".toString())

        androidTest {
            java.srcDirs += 'tests/androidTest/src/java'
            res.srcDirs += 'tests/androidTest/res'
            manifest.srcFile 'tests/androidTest/AndroidManifest.xml'
        }
    }

    lint {
        // Instead of failing the build due to missing translations, just inform us to avoid
        // mistakes during manual import
        informational 'MissingTranslation'
        disable 'GradlePluginVersion'
    }

    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    packagingOptions.resources.excludes += [
        "**/*.bin",
        "**/*.properties",
        "**/*.version",
        "kotlin/**",
        "META-INF/services/**",
        "META-INF/com/**",
    ]

    tasks.withType(JavaCompile) {
        options.errorprone {
            enabled = true
            disableWarningsInGeneratedCode = true   // for @Generated (e.g., Dagger/Hilt, Room)
            excludedPaths = '.*/build/generated/.*' // for other generated code

            // Uncomment to patch the files for which Error Prone have suggested replacements
            // errorproneArgs.add("-XepPatchChecks:" + [
            // ].join(","))
            // errorproneArgs.add("-XepPatchLocation:IN_PLACE")
        }
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
            all {
                it.systemProperties["robolectric.pixelCopyRenderMode"] = "hardware"
                maxHeapSize = "6144m"
            }
        }
    }

    buildFeatures {
        buildConfig = true
    }
}

addCompileOnlyJar(jars.android_hidden, /*requiredByAndroidTest*/ true)

dependencies {
    implementation libs.annotation
    implementation libs.biometric
    implementation libs.collection
    implementation libs.core
    implementation libs.livedata
    implementation libs.material
    implementation libs.preference
    implementation libs.recyclerview
    implementation libs.viewmodel
    implementation libs.hilt.android
    kapt libs.hilt.compiler
    kaptTest libs.hilt.compiler

    implementation libs.room.runtime
    kapt libs.room.compiler

    implementation project(path: ':SettingsLib:BannerMessagePreference')
    implementation project(path: ':SettingsLib:CollapsingToolbarBaseActivity')
    implementation project(path: ':SettingsLib:LayoutPreference')
    implementation project(path: ':SettingsLib:SettingsTheme')
    implementation project(path: ':SettingsLib:TwoTargetPreference')

    testImplementation libs.arch.core.testing
    testImplementation libs.awaitility
    testImplementation libs.hamcrest
    testImplementation (libs.espresso) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    testImplementation (libs.espresso.contrib) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    testImplementation libs.junit
    testImplementation libs.hilt.android.testing
    testImplementation libs.mockito
    mockitoAgent(libs.mockito)
    testImplementation libs.test.core
    testImplementation libs.robolectric
    testImplementation libs.robolectric.androidAll
    testImplementation libs.roborazzi
    testImplementation libs.roborazzi.junit.rule
    testImplementation libs.room.testing
    testImplementation libs.test.ext.junit

    androidTestImplementation libs.hamcrest
    androidTestImplementation (libs.junit) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    androidTestImplementation (libs.hilt.android.testing) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    androidTestImplementation (libs.test.ext.junit) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    androidTestImplementation (libs.test.rules) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    androidTestImplementation (libs.test.runner) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }

    implementation libs.errorprone.annotations
    errorprone libs.errorprone
    annotationProcessor libs.errorprone
    testAnnotationProcessor libs.errorprone
    androidTestAnnotationProcessor libs.errorprone
}

kapt {
    correctErrorTypes true
}

kover {
    useJacoco()
    reports {
        filters {
            excludes {
                // excludes class by fully-qualified JVM class name, wildcards
                // '*' and '?' are available
                classes(
                    '*BuildConfig',
                    '*.Hilt_*',
                    '*_ComponentTreeDeps',
                    '*_HiltComponents*',
                    '*_Impl',
                    '*_Impl\$*',
                )
                // excludes all classes located in specified package and it
                // subpackages, wildcards '*' and '?' are available
                packages(
                    'com.github.iusmac.sevensim.inject',
                    'com.github.iusmac.sevensim.ui.components',
                    'hilt_aggregated_deps',
                    'dagger.hilt.internal.*',
                )
                // excludes all classes and functions, annotated by specified
                // annotations, wildcards '*' and '?' are available
                annotatedBy('*Generated*')
            }
        }
    }
}

/**
 * Describe the tag relative to a commit-ish using "git describe".
 *
 * The result from the git describe command will be transformed as follows:
 * "TAG-N-g<commit-ish>" = ["TAG", "N", "commit-ish"]
 * "<commit-ish>"        = [null, 0, "commit-ish"]
 */
def gitDescribeTag(final String pattern, final String commitIsh) {
    final def describedTag = String.format('git describe --always --tags --long --match=%s %s',
            pattern, commitIsh).execute([], project.rootDir).text.trim().split('-')
    final def tag, commitsSinceLastTag
    def headCommit
    if (describedTag.size() > 2) {
        tag = describedTag[0..-3].join('-')
        (commitsSinceLastTag, headCommit) = describedTag[-2..-1]
        headCommit = headCommit.substring(1)
    } else if (describedTag.size() > 0) {
        tag = null
        headCommit = describedTag[0]
        commitsSinceLastTag = 0
        assert(headCommit != null && !headCommit.trim().isEmpty())
    } else {
        throw new AssertionError('The output from `git describe` command is empty.')
    }
    return [tag, commitsSinceLastTag, headCommit]
}

/**
 * Check whether it was asked to opt-in for debug logging on releases with R8.
 *
 * The output of this function is determined via:
 * - Gradle argument: -PreleaseDebugOpt=[true|false]
 * - Environment variable: RELEASE_DEBUG_OPT=[true|false]
 *
 * Boolean as Integer is allowed.
 */
def isReleaseDebugOpt() {
    final def String debugOpt = [
        System.getenv('RELEASE_DEBUG_OPT'),
        project.properties.releaseDebugOpt
    ]
    return debugOpt.contains('1') || debugOpt.contains('true')
}
