pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

plugins {
    id 'com.android.settings' version '8.8.2'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = '7SIM'

include ':SettingsLib:BannerMessagePreference'
include ':SettingsLib:CollapsingToolbarBaseActivity'
include ':SettingsLib:LayoutPreference'
include ':SettingsLib:SettingsTheme'
include ':SettingsLib:TwoTargetPreference'

android {
    compileSdk 35
    minSdk 29
    targetSdk 35
    buildToolsVersion '35.0.0'
}
