plugins {
    id 'com.android.library'
}

android {
    namespace 'com.android.settingslib.color'

    defaultConfig {
        minSdk 28
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    sourceSets {
        main {
            res.srcDirs = ['../fwb/packages/SettingsLib/Color/res']
        }
    }
}
